### ISSUE TITLE
Frequent `socket hang up` errors

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-trace-nodejs#626]
Since I set up Stackdriver Trace using this Node module, some new errors appear regularly in Stackdriver Error Reporting.

The worst is that they are not all grouped together, as they do not seem to all have the same stack trace.

Here are examples of stack traces:
`````
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at /app/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`````

`````
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at /app/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`````

**Comment by ofrobots** [comment]
In what environment did you encounter these errors?

**Comment by steren** [comment]
App Engine Flex.

**Comment by kjin** [comment]
@steren Please let us know if you have any other details here, but I don't think this is actionable given the current information, since the errors seem to be generic Node errors. Closing for now.
