### ISSUE TITLE
Exception: cannot read property bindEmitter of Null

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#70]
Run into this just now. Seems like we need a test for the path where we fail to get a project number. We need to completely disable the agent in such cases.

```shell
~/src/bookshelf2/bookshelf 2-structured-data
❯ node app.js
App listening at http://:::8080
ERROR:@google/cloud-trace: Unable to acquire the project number from metadata service. Please provide a valid project number as an env. variable, or through config.projectId passed to start().Error: Could not auto-discover project-id. Please export GCLOUD_PROJECT_NUM with your numeric project id
TypeError: Cannot read property 'bindEmitter' of null
    at middleware (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/@google/cloud-trace/lib/hooks/userspace/hook-express.js:40:12)
    at Layer.handle [as handle_request] (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:312:13)
    at /Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:312:13)
    at /Users/ofrobots/src/bookshelf2/bookshelf/node_modules/express/lib/router/index.js:280:7
```

**Comment by matthewloring** [comment]
The problem is that middleware is being registered before the agent disables, I see two choices:
a) if we find that the agent is disabled while executing the middleware, just call `next` immediately and noop out (minimal overhead but middleware stays on even without tracing)
b) use undocumented (non-public) api to try to slice out our middleware but once sliced out, the middleware could not be reenabled in the future

I would be inclined to implement the first because it's less error prone and doesn't rely on undocumented APIs but it does incur a slightly performance overhead (as opposed to having no middleware)

I can investigate other possibilities for removing the middleware using the express public api.
