### ISSUE TITLE
NetworkingError: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by dippi** [GoogleCloudPlatform/cloud-trace-nodejs#763]
Hi, we intermittently had this issue while uploading a file to S3 using aws-sdk.
```
NetworkingError: Can't set headers after they are sent.
    at ClientRequest.setHeader (_http_outgoing.js:371:11)
    at Object.requestTrace [as request] (/data/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-http.js:124:13)
    at Object.request (https.js:206:15)
    at features.constructor.handleRequest (/data/node_modules/aws-sdk/lib/http/node.js:42:23)
    at executeSend (/data/node_modules/aws-sdk/lib/event_listeners.js:304:29)
    at Request.SEND (/data/node_modules/aws-sdk/lib/event_listeners.js:318:9)
    at Request.callListeners (/data/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/data/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/data/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/data/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/data/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /data/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/data/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/data/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/data/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/data/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /data/node_modules/aws-sdk/lib/event_listeners.js:220:9
    at finish (/data/node_modules/aws-sdk/lib/config.js:320:7)
    at /data/node_modules/aws-sdk/lib/config.js:338:9
    at Credentials.get (/data/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/data/node_modules/aws-sdk/lib/config.js:332:24)
    at Config.getCredentials (/data/node_modules/aws-sdk/lib/config.js:352:9)
    at Request.SIGN (/data/node_modules/aws-sdk/lib/event_listeners.js:192:22)
    at Request.callListeners (/data/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/data/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/data/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/data/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/data/node_modules/aws-sdk/lib/state_machine.js:14:12)
```
The stack points here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/plugins/plugin-http.ts#L147-L148 
I have to admit I haven't collected much information at the moment, so tell me if there is something you'd like to know to understand the issue better.
Any idea on what's happening and how to solve it?
Thanks!

( @Macr0s FYI )

**Comment by kjin** [comment]
Hi @dippi, which version of Node are you using? We've encountered a similar problem in the past but I might have only patched it for `http` (judging from the stack trace you are using the `https` module).

**Comment by dippi** [comment]
Hi @kjin, we are using version v8.11.x

**Comment by kjin** [comment]
I believe I've pinned down the issue -- in short, our HTTP instrumentation will fail if `Expect` is added as an outgoing header. This is because Node has a special case where it prohibits additional headers if the `Expect` header is detected. (I am not sure if this is intentional.) The AWS SDK [adds this header](https://github.com/aws/aws-sdk-js/blob/5880e725ca12f559fcead5cac2c305e55de1ccfb/lib/services/s3.js#L252) if the file is greater than 1MB.

BTW, your provided stack trace seems to suggest Node 7 (given the line numbers), though this issue is present in Node 8 as well.

I am working on a fix for this now.

**Comment by dippi** [comment]
We tested and the issue seems indeed to be related to file size.
As for the Node version, the stack trace might come from an outdated testing instance with Node 7, sorry for the inaccuracy.

I'm pleased to see that you already merged a fix, so thanks for the quick response to the issue!
To test and benefit from the fix should we move our dependency to master or wait until the next release? (in the latter case, what is a reasonable eta?

**Comment by kjin** [comment]
I just put out a release for 2.10.1, so the fix should be out now 😄
